name: Release
on: workflow_dispatch

jobs:
  check-if-tag:
    name: Set Package Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.deployment.outputs.version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Set Variables
        id: deployment
        shell: bash
        run: |
          if [ $(git describe --exact-match --tags HEAD &> /dev/null; echo $?) == 0 ]; then
            echo "version=$(git describe --exact-match --tags HEAD)" >> $GITHUB_OUTPUT
          else
            echo "fatal: no tag detected for HEAD. Workflow will now stop."
            exit 128;
          fi

  release:
    name: Release
    needs: [check-if-tag]
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
  
      - name: Setup NuGet
        uses: nuget/setup-nuget@v3
  
      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install .NET iOS Workload
        run: dotnet workload install ios

      - name: Build .NET Core Projects
        run: dotnet build managed-midi.Core.slnf

      - name: Build .NET Framework Projects
        run: msbuild managed-midi.Windows.slnf -restore -p:RestorePackagesConfig=true

      - name: Build Xamarin Projects
        run: msbuild managed-midi.Xamarin.slnf -restore -p:AndroidSdkDirectory="$env:ANDROID_HOME" -p:JavaSdkDirectory="$env:JAVA_HOME_11_X64"

      - name: Pack Projects
        run: nuget pack -Version ${{ needs.check-if-tag.outputs.version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: managed-midi.${{ needs.check-if-tag.outputs.version }}
          path: ./*.nupkg

      - name: Publish to NuGet 
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
